project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!materials/workshop/"

website:
  title: "Get Started with Quarto"
  twitter-card:
    card-style: summary_large_image
    description: "rstudio::conf-2022 2 day workshop on getting started with Quarto"
    image: "https://raw.githubusercontent.com/rstudio-conf-2022/get-started-quarto/main/preview.png"
  navbar:
    background: "#447099"
    left:
      - href: index.qmd
        text: readme
      - text: Day 1
        menu: 
          - href: materials/01-intro-quarto.qmd
            text: "Intro to Quarto"
          - href: materials/02-authoring.qmd
            text: "Authoring Quarto"
          - href: materials/03-computation-editors.qmd
            text: "Code and Editors"
          - href: materials/04-static-documents.qmd
            text: "Static Documents" 
      - text: Day 2
        menu: 
          - href: materials/05-presentations.qmd
            text: "Presentations"
          - href: materials/06-websites.qmd
            text: "Websites & Books"
          - href: materials/07-plots-tables.qmd
            text: "Plots & Tables"
          - href: materials/08-advanced-knitr.qmd
            text: "Advanced Quarto"
    right: 
      - icon: github
        href: https://github.com/rstudio-conf-2022/get-started-quarto
      - icon: twitter
        href: https://twitter.com/quarto_pub
  sidebar: 
    style: docked
    contents: 
      - section: "Day 1"
        contents: 
          - href: materials/01-intro-quarto.qmd
            text: "Intro to Quarto"
          - href: materials/02-authoring.qmd
            text: "Authoring Quarto"
          - href: materials/03-computation-editors.qmd
            text: "Code and Editors"
          - href: materials/04-static-documents.qmd
            text: "Static Documents"
      - section: "Day 2"
        contents:
          - href: materials/05-presentations.qmd
            text: "Presentations"
          - href: materials/06-websites.qmd
            text: "Websites & Books"
          - href: materials/07-plots-tables.qmd
            text: "Plots & Tables"
          - href: materials/08-advanced-knitr.qmd
            text: "Advanced Quarto"

format:
  html:
    theme: 
      - litera
      - style.css
    toc: true
    
execute: 
  freeze: true